{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It is an error to call this function before "},{"type":"codeVoice","code":"g_subprocess_wait()"},{"type":"text","text":" has"},{"type":"text","text":" "},{"type":"text","text":"returned."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gio\/subprocessprotocol\/successful"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/GIO\/documentation\/GIO\/SubprocessProtocol\/successful","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Checks if the process was “successful”.  A process is considered"},{"type":"text","text":" "},{"type":"text","text":"successful if it exited cleanly with an exit status of 0, either by"},{"type":"text","text":" "},{"type":"text","text":"way of the "},{"type":"codeVoice","code":"exit()"},{"type":"text","text":" system call or return from "},{"type":"codeVoice","code":"main()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"successful","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","externalID":"s:3GIO18SubprocessProtocolPAAE10successfulSbvp","extendedModule":"GIO","modules":[{"name":"GIO"}]},"hierarchy":{"paths":[["doc:\/\/GIO\/documentation\/GIO","doc:\/\/GIO\/documentation\/GIO\/SubprocessProtocol"]]},"references":{"doc://GIO/documentation/GIO/SubprocessProtocol/successful":{"role":"symbol","title":"successful","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks if the process was “successful”.  A process is considered"},{"type":"text","text":" "},{"type":"text","text":"successful if it exited cleanly with an exit status of 0, either by"},{"type":"text","text":" "},{"type":"text","text":"way of the "},{"type":"codeVoice","code":"exit()"},{"type":"text","text":" system call or return from "},{"type":"codeVoice","code":"main()"},{"type":"text","text":"."}],"identifier":"doc:\/\/GIO\/documentation\/GIO\/SubprocessProtocol\/successful","kind":"symbol","type":"topic","url":"\/documentation\/gio\/subprocessprotocol\/successful"},"doc://GIO/documentation/GIO/SubprocessProtocol":{"role":"symbol","title":"SubprocessProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubprocessProtocol"}],"abstract":[{"type":"codeVoice","code":"GSubprocess"},{"type":"text","text":" allows the creation of and interaction with child"},{"type":"text","text":" "},{"type":"text","text":"processes."}],"identifier":"doc:\/\/GIO\/documentation\/GIO\/SubprocessProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubprocessProtocol"}],"url":"\/documentation\/gio\/subprocessprotocol"},"doc://GIO/documentation/GIO":{"role":"collection","title":"GIO","abstract":[],"identifier":"doc:\/\/GIO\/documentation\/GIO","kind":"symbol","type":"topic","url":"\/documentation\/gio"}}}